# Generated by Django 3.2 on 2021-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='alias',
            new_name='Coursefullform',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='name',
            new_name='Coursename',
        ),
        migrations.AddField(
            model_name='hero',
            name='Availabilty',
            field=models.BooleanField(default=False),
        ),
    ]
