# Generated by Django 3.2 on 2021-05-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_hero_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=60)),
                ('Eventdescription', models.CharField(max_length=500)),
                ('Date', models.DateField()),
            ],
        ),
    ]
